# Nim bindings for libgccjit. Autogenerated from the C header file
# using c2nim tool > https://github.com/nim-lang/c2nim
#
# (c) 2025 George Lemon | GPLv3 License
#          Made by Humans from OpenPeeps
#          https://github.com/openpeeps/libdatachannel-nim

import ./gccjit/wrapper
export wrapper